### ISSUE TITLE
Error While Checking Access

### ISSUE THREAD

**Issue by craigmc08** [CIF-Rochester/GateKeeper#6]
Relevant logs:

```
[2023-10-21 20:46:51] CRITICAL Unexpected exception. Crashing...
Traceback (most recent call last):
  File "XXX/main.py", line 81, in <module>
    main()
  File "XXX/main.py", line 64, in main
    account = Account(swipe, client, logger, config)
  File "XXX/account.py", line 17, in __init__
    self.user = client.user_find(o_employeenumber=swipe.id) # returns a dictionary with the user's info
  File "XXX/.venv/lib/python3.8/site-packages/python_freeipa/client_meta.py", line 26093, in user_find
    return self._request(method, _args, _params)
  File "XXX/.venv/lib/python3.8/site-packages/python_freeipa/client.py", line 327, in _request
    raise Unauthorized()
python_freeipa.exceptions.Unauthorized: Unauthorized: bad credentials.
```

Previous log messages are not relevant, they occurred >14 hours before the crash.

The crash is fixed by #5, but this error should still be looked into.

**Comment by craigmc08** [comment]
With the changes from #5, the program does not crash but there are new issues:

1. It's not a one off error: within 24 hours of starting the program, the error starts occuring on *every* swipe. This points to this error being a login session timeout.

2. Because an error occurs while building the `Account` object, `account` is never assigned. Because of python's weird scoping, the variable keeps its value from the previous interation. So, if it happens that the last swipe before the session timeout was for an account with access, **every** subsequent swipe until restart results in the door being unlocked.

**Comment by fenwaypowers** [comment]
Fixed by https://github.com/CIF-Rochester/GateKeeper/pull/8
